services:
  web:
    image: todo-tailwind:latest
    ports:
      - "8082:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
